kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  namespace: nfs-subdir-external-provisioner
spec:
  storageClassName: nfs-default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

