---
- name: Install Kubernetes nodes
  hosts: all
  become: true


  vars:
    system_services:
      - "rpcbind.service"     # NFS
# Latest K3s does not need docker
#      - "docker.service"


  tasks:
    - name: "Populate facts"
      ansible.builtin.service_facts:

#    - name: "Set timezone"
#      community.general.timezone:
#        name: "Europe/Budapest"


    - name: "Install packages"
      ansible.builtin.apt:

        name:
          - apt-file          # Find info about packages
          - vim               # Text editor
          - nano              # Text editor
          - dnsutils          # Debug DNS
          - net-tools         # Debug network, netstat / route / arp / ifconfig
          - inetutils-ping    # Debug network, ping
          - netcat-openbsd    # Debug network, tcp
          - nmap              # Debug network, scan
          - ntpsec            # Debug NTP
          - jq                # JSON processing
          - pwgen             # Security: password generation
          - libnfs-utils      # NFS client utilities
          - nfs-common        # NFS client utilities
          - parted            # Block device partitioning for SDS, eg. Longhorn
# Latest K3s does not need docker
#          - docker.io         # Kubernetes container runtime on Debian based distros
        state: present

    - name: "Enable and start services"
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items: "{{ system_services }}"

  handlers:
    - name: "Reboot server"
      ansible.builtin.debug:
        msg: "You should reboot the host"

    - name: "Restart systemd"
      ansible.builtin.systemd:
        daemon-reload: true
