apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certmanager-test
  namespace: certmanager
spec:
  dnsNames:
    - example.com
  secretName: certmanager-test-certificate
  issuerRef:
    name: selfsigned
