kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: {{ .Release.Namespace | quote }}
data:
  sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    insecure: false
    ca: /etc/ldap-ca/ca.crt
    url: ldaps://idmsrv.idm.example.com:636
    bindDN: uid=mycluster-idp,cn=users,cn=accounts,dc=idm,dc=example,dc=com
    bindPassword:
      file: "/etc/secrets/bindPassword"
    rfc2307:
      groupsQuery:
        baseDN: "cn=groups,cn=accounts,dc=idm,dc=example,dc=com"
        scope: sub
        filter: "(&(objectClass=ipausergroup)(cn=os_*))"
        derefAliases: never
        pageSize: 0
      groupUIDAttribute: dn
      groupNameAttributes: [ cn ]
      groupMembershipAttributes: [ member ]
      usersQuery:
        baseDN: "cn=users,cn=accounts,dc=idm,dc=example,dc=com"
        scope: sub
        derefAliases: never
        pageSize: 0
      userUIDAttribute: dn
      userNameAttributes: [ uid ]
      tolerateMemberNotFoundErrors: true
      tolerateMemberOutOfScopeErrors: true
