environments:
  example-env:

# You must provide a custom values file called values--example-env.yaml
# As a start you can get the char's default values with by executing 
#
# helm show values helm-repo/chart-name > values--example-env.yaml
#
# Code linters / schema validators might get confused
# by the compact syntax used here to integrate
# the main helmfile.yaml and environments.yaml 
# If this is the case, you can provide an empty 
# schema definition to your linter or just break
# up this file to two distinct files

---

repositories:

  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

  - name: longhorn
    url: https://charts.longhorn.io

  # Cert-manager
  - name: jetstack
    url: https://charts.jetstack.io

  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/

  - name: harbor
    url: https://helm.goharbor.io

  - name: minio
    url: https://charts.min.io/


helmDefaults:
  atomic: true
  cleanupOnFail: true


templates:
  default:
    namespace: "{{`{{ .Release.Name }}`}}"
    values:
      - "./{{`{{ .Release.Name }}`}}/values--{{ .Environment.Name }}.yaml"
    missingFileHandler: Error
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./{{`{{ .Release.Name }}`}}/custom_resources/"
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "./{{`{{ .Release.Name }}`}}/custom_resources/"

releases:

  # NFS subdir autoprovisioner
  # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md
  - name: nfs-subdir-external-provisioner
    inherit:
      - template: default
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    installed: false

  # Longhorn
  # https://longhorn.io/docs/
  - name: longhorn
    inherit:
      - template: default
    chart: longhorn/longhorn
    version: 1.8.0
    installed: true

  # Cert-Manager
  # https://cert-manager.io/docs/installation/helm/
  - name: certmanager
    inherit:
      - template: default
    chart: jetstack/cert-manager
    # helm search repo cert-manager
    # Chart version equals to appversion
    version: 1.16.1
    installed: true

  # Kubernetes Dashboard
  - name: kube-dashboard
    inherit:
      - template: default
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.10.1
    # This worth a word...
    # In most cases you do not need to specify the NameSpace where a given 
    # release is installed, but as the default template here forces all releases
    # to go on their own NameSpace, and the NS has the same name as the release,
    # in "needs" you have to use the "namespace/release" notation
    needs:
      - certmanager/certmanager
      - longhorn/longhorn
    installed: true

  # Harbor
  # https://github.com/goharbor/harbor-helm
  - name: harbor
    inherit:
      - template: default
    chart: harbor/harbor
    # helm search repo harbor
    # Chart version 1.16.2 --> 2.12.2
    version: 1.16.2
    needs:
      - certmanager/certmanager
      - longhorn/longhorn
    installed: true

  # Minio
  # "Vanilla" Minio Helm chart
  # https://github.com/minio/minio/tree/master/helm/minio
  - name: minio
    inherit:
      - template: default
    chart: minio/harbor
    # helm search repo harbor
    # Chart version 1.16.2 --> 2.12.2
    version: 1.16.2
    needs:
      - certmanager/certmanager
      - longhorn/longhorn
    installed: false
