environments:
  example-env:

# You must provide a custom values file called values--example-env.yaml
# As a start you can get the char's default values with by executing 
#
# helm show values helm-repo/chart-name > values--example-env.yaml
#

---

repositories:

  - name: nfs-subdir-external-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/


helmDefaults:
  atomic: true
  cleanupOnFail: true


templates:
  default:
    namespace: "{{`{{ .Release.Name }}`}}"
    values:
      - "./{{`{{ .Release.Name }}`}}/values--{{ .Environment.Name }}.yaml"
    missingFileHandler: Error
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "./{{`{{ .Release.Name }}`}}/custom_resources/"
      - events: ["postuninstall"]
        showlogs: true
        command: "kubectl"
        args:
          - "delete"
          - "-f"
          - "./{{`{{ .Release.Name }}`}}/custom_resources/"

releases:

  # NFS subdir autoprovisioner
  # https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/blob/master/charts/nfs-subdir-external-provisioner/README.md
  - name: nfs-subdir-external-provisioner
    inherit:
      - template: default
    chart: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
    version: 4.0.18
    installed: false

  # Kubernetes Dashboard
  - name: kube-dashboard
    inherit:
      - template: default
    chart: kubernetes-dashboard/kubernetes-dashboard
    version: 7.10.0
    installed: false

