---

- name: Reset (remove all data files) containerhost
  become: false
  hosts:
    all

  tasks:
    - name: Reset containerhost
      ansible.builtin.shell:
        cmd: |
          podman rm --force --all
          podman rmi --force --all
          podman pod rm -af
          rm -rf /home/{{ ansible_user }}/container-projects
          rm -rf /home/{{ ansible_user }}/.config
          rm -rf /home/{{ ansible_user }}/.local
          sudo rm -rf /etc/systemd/user/podman-compose@.service

      args:
        chdir: .
        creates: /tmp/run-task-unconditionally
