
vars:
  system_services:
    - "chrony.service"


pre_tasks:
  - name: "Update all packages"
    ansible.builtin.dnf:
      name: "*"
      state: latest
      update_cache: yes

tasks:
  - name: "Populate facts"
    ansible.builtin.service_facts:

  - name: "Set timezone"
    community.general.timezone:
      name: "Europe/Budapest"


  - name: "Install packages"
    ansible.builtin.dnf:

      name:
        - bind-utils        # Debug DNS
        - net-tools         # Debug network, eg ping
        - nc                # Debug network, tcp
        - nmap              # Debug network, scan
        - ntpsec            # Debug NTP 
        - jq                # JSON processing
        - pwgen             # Security: password generation
        - podman            # Podman engine
        - container-tools   # Buildah, Skopeo, CRIU (snapshot container state to disk), Udica (selinux policy generator for containers)
      state: present

  - name: "Enable and start services"
    ansible.builtin.service:
      name: "{{ item }}"
      enabled: true
      state: started
    with_items: "{{ system_services }}"

  - name: "Set up host firewall"
    import_role:
      name: "linux-system-roles.firewall"
    vars:
      firewall:
        - zone:    "external"
          port:    "80/tcp"
          state:   enabled

        - zone:    "external"
          port:    "443/tcp"
          state:   enabled


handlers:
  - name: "Reboot server"
    debug:
      msg: "You should reboot the host"

  - name: "Restart systemd"
    ansible.builtin.systemd:
      daemon-reload: true