apiVersion:   v2
name:         os-idm-integration
type:         application
version:      2.0.0
appVersion:   "1.0.0"
description:  "Red Hat Identity Manager integration with OpenShift, as an identity provider. Provides a local cluster admin user for disaster recovery."