apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster

spec:

  identityProviders:

    - name: "Local users"
      mappingMethod: claim
      type: HTPasswd
      htpasswd:
        fileData:
          name: idp-htpasswd

    - name: "Identity Manager"
      mappingMethod: claim
      type: LDAP
      ldap:
        url: >-
          ldaps://idmsrv.idm.example.com:636/cn=accounts,dc=idm,dc=example,dc=com?uid?sub?(&(objectClass=posixaccount)(memberOf=cn=os_access,cn=groups,cn=accounts,dc=idm,dc=example,dc=com))
        insecure: false
        ca:
          name: idm--ldap-ca
        bindDN: 'uid=mycluster-idp,cn=users,cn=accounts,dc=idm,dc=example,dc=com'
        bindPassword:
          name: idm--ldap-bind-password
        attributes:
          email:
            - mail
          id:
            - dn
          name:
            - cn
          preferredUsername:
            - uid
